config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :posts

  resources :plants
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static#home"
  get '/search' => 'search#index'
  # for the search function on the search page
  post '/search' => 'search#index'
  get '/feed' => 'static#feed'
  post '/plants/:id/add' => 'plants#add', as: :plant_add
  post '/plants/:id/remove' => 'plants#remove', as: :plant_remove
  post '/recipe/add' => 'recipe#add', as: :recipe_add
  post '/recipe/:id/remove' => 'recipe#remove', as: :recipe_remove
  get '/feed' => 'static#feed'
  # gives users a customized paged based on username and also sets a profile_path
  get '/:username(/:page)' => 'static#profile', as: :profile

end

app/models/plant.rb
class Plant < ApplicationRecord
	# enum size: [:Small, :Medium, :Large]
	has_many :user_plants
	has_many :users, through: :user_plants
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/default_pic.svg"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  	validates :size, presence: true, numericality: { in: 0..2 }

  	def to_word
  		if (size === 0)
  			"Small"
  		elsif (size === 1)
  			"Medium"
  		elsif (size === 2)
  			"Large"
			else
				"WE'RE SORRY, SOMETHING TERRIBLE WENT WRONG!!! WE DON'T HAVE THAT INFO!"
  		end
  	end

    def to_eat
      if (edible == true)
        "Edible"
      elsif (edible == false)
        "Decorative"
      else
        "WE'RE SORRY, SOMETHING TERRIBLE WENT WRONG!!! WE DON'T HAVE THAT INFO!"
      end
    end

    def is_herb
      if (herb == true)
        "Yes, this is an herb"
      elsif (herb == false)
        "No, this is not an herb"
      else
        "WE'RE SORRY, SOMETHING TERRIBLE WENT WRONG!!! WE DON'T HAVE THAT INFO!"
      end
    end

    def is_fruitveg
      if (fruitveg == true)
        "Yes, this is a fruit or vegetable"
      elsif (fruitveg == false)
        "No, this is not a fruit or vegetable"
      else
        "WE'RE SORRY, SOMETHING TERRIBLE WENT WRONG!!! WE DON'T HAVE THAT INFO!"
      end
    end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # Add plants to userplants
  def add
    # define current user
   @user = current_user
    # look for the plant by plant.id
   @plant = Plant.find(params[:id])
    # define if the userplant table exists
   @userplant = UserPlant.find_by(plant_id: params[:id], user_id: current_user.id)
   if @userplant
    #  if it doesnt exist, then push the plant into the userplant join table
   else
     @user.plants << @plant
   end
   redirect_to plants_path
  end

  def remove
    @plant = Plant.find(params[:id])
    @userplant = UserPlant.find_by(plant_id: params[:id], user_id: current_user.id)
    unless @userplant.nil?
      @userplant.destroy
    else
    end
    redirect_back(fallback_location: root_path)
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.require(:plant).permit(:name, :sname, :care, :water, :sale, :size, :image)
    end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/_form.html.erb
<div id="plantForm">

<%= form_with(model: plant, local: true) do |form| %>
  <% if plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :plant_name %>
  </div>

  <div class="field">
    <%= form.label :Botanical_Name %>
    <%= form.text_field :sname, id: :plant_sname %>
  </div>

  <div class="field">
    <%= form.label :care %><br />
    <%= form.text_area :care, id: :plant_care %>
  </div>

  <div class="field">
    <%= form.label :water_times_per_week %>
    <%= form.number_field :water, id: :plant_water %>
  </div>

  <div class="field">
    <%= form.label :Edible_or_decorative %>
    <%= form.radio_button(:edible, true) %>
    <%= label_tag(:edible, "Edible") %>
    <%= form.radio_button(:edible, false) %>
    <%= label_tag(:edible, "Decorative") %>
  </div>

  <div class="field">
    <%= form.label :Herb %>
    <%= form.radio_button(:herb, true) %>
    <%= label_tag(:herb, "Yes, this is an herb") %>
    <%= form.radio_button(:herb, false) %>
    <%= label_tag(:herb, "No, this is not an herb") %>
  </div>

  <div class="field">
    <%= form.label :Fruit_or_Vegetable %>
    <%= form.radio_button(:fruitveg, true) %>
    <%= label_tag(:fruitveg, "Yes, this is a fruit or vegetable") %>
    <%= form.radio_button(:fruitveg, false) %>
    <%= label_tag(:fruitveg, "No, this is not a fruit or vegetable") %>
  </div>

  <div class="field">
    <%= form.label :sale_link %>
    <%= form.text_field :sale, id: :plant_sale %>
  </div>

  <div class="field">
    <%= form.label :Size %><br />
    <%= form.radio_button(:size, 0) %>
    <%= label_tag(:size, "Small: <12in") %>
    <%= form.radio_button(:size, 1) %>
    <%= label_tag(:size, "Medium: 12-24in") %>
    <%= form.radio_button(:size, 2) %>
    <%= label_tag(:size, "Large: >24in") %>
  </div><br />

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :plant_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/plants/edit.html.erb
<% if current_user.admin? %>
<div id="plantEdit">
  <h1>Editing Plant</h1>
    <%= render 'form', plant: @plant %>

    <%= link_to 'Back To Plant Page', @plant %> |
    <%= link_to 'Back To All Plants', plants_path %>
 </div>
<% else %>
  <center>
    You don't have access to this page!!!
  </center>
<% end %>

app/views/plants/index.html.erb
<div id="plantIndexPage">
<h1>Plants</h1>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'Add New Plant', new_plant_path, class: "newplantlink" %><br><br>
<% else %>
<% end %>
  <% @plants.each do |plant| %>
        <span class="plantPreview">
        	<a href="/plants/<%= plant.id %>">
        	<%= image_tag plant.image.url %></a><br />

          <% if UserPlant.find_by(plant_id: plant.id, user_id: current_user.id) %>
            <%= button_to 'Remove Plant', plant_remove_path(plant) %>
          <% else %>
            <%= button_to 'Add Plant', plant_add_path(plant) %>
          <% end %>

          <% if user_signed_in? && current_user.admin? %>
          <br>
        	<%= link_to 'Edit', edit_plant_path(plant) %>
        	<%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% else %>
          <% end %>
        </span>
  <% end %>

</div>

app/views/plants/new.html.erb
<div id="newPlantDiv">
	<% if current_user.admin? %>
		<h1>Add New Plant</h1>
			<%= render 'form', plant: @plant %>
			<%= link_to 'Back To Plants', plants_path %>
	<% else %>
		You don't have access to this page!!!
	<% end %>
</div>

app/views/plants/show.html.erb
<div id="plantShowPage">
  <div id="plantShowInfo" class="col-sm-6">

<p>
  <strong class ="plantName"><%= @plant.name %></strong>
</p><br /><br />

<p>
  <strong>Botanical Name:</strong>
  <%= @plant.sname %>
</p>

<p>
  <strong>Care:</strong>
  <%= @plant.care %>
</p>

<p>
  <strong>Water:</strong>
  <%= @plant.water %> times per week
</p>

<p>
  <strong>Edible or Decorative:</strong>
  <%= @plant.to_eat %>
</p>

<p>
  <strong>Herb:</strong>
  <%= @plant.is_herb %>
</p>

<p>
  <strong>Fruit/Vegetable:</strong>
  <%= @plant.is_fruitveg %>
</p>

<p>
  <strong>Size:</strong>
  <%= @plant.to_word %>
</p>

<p>
  <strong>Buy what you need to get started:</strong>
  <a href="<%= @plant.sale %>" class="buyLink">Get Seeds</a>
</p>

<% if UserPlant.find_by(plant_id: @plant.id, user_id: current_user.id) %>
  <%= button_to 'Remove From My Plants', plant_remove_path(@plant) %>
<% else %>
  <%= button_to 'Add To My Plants', plant_add_path(@plant) %>
<% end %>

  </div>
  <div id="plantShowPic" class="col-sm-6">
  <!-- <%# @plant.image %> -->
  <%= image_tag @plant.image.url %>
  <% if user_signed_in? && current_user.admin? %>
  <br>
    <%= link_to 'Edit', edit_plant_path(@plant) %> |
    <%= link_to 'Back To All Plants', plants_path %>
  <% else %>
  <% end %>
  </div>